export enum SystemConfigKey {
  LATEST_BLOCK_CRAWLED_TIME = 'LATEST_BLOCK_CRAWLED_TIME',
  CURRENT_MILE_TIME_BUILD_CANDLE_1M = 'CURRENT_MILE_TIME_BUILD_CANDLE_1M',
  MAX_JOB_BUILD_CANDLE_1M = 'MAX_JOB_BUILD_CANDLE_1M',
}
